services:
  - type: web
    name: siigo-api
    env: docker
    dockerfilePath: ./Dockerfile.api
    dockerContext: .
    dockerCommand: sh -c "alembic upgrade head ; uvicorn api.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: https://TU-STREAMLIT.onrender.com

  - type: web
    name: siigo-streamlit
    env: docker
    dockerfilePath: ./Dockerfile.streamlit
    dockerContext: .
    dockerCommand: sh -c "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: API_URL
        value: https://TU-API.onrender.com
